Repository Rick-mad-lab/Todolist, pull requests merged in 2022-10, with the labels that each got.

#26 Updated the new theme for TODOLIST
  style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#23 Check user input
  images/check.png
  images/plus.png
  images/trash1.png
  index.html
  main.js
  style.css
Labels: enhancement, hacktoberfest

#32 Add Light Theme User Experience for To-Do List Web Version
  User Experience/Design.md
  User Experience/Image/Screenshot from 2022-10-01 18-53-27.png
  User Experience/LightIcons/Icon-Fill-all-done.png
  User Experience/LightIcons/Icon-Fill-plus-circle.png
  User Experience/LightIcons/Icon-Fill-trash-2.png
  User Experience/LightIcons/Mask.png
  User Experience/LightIcons/image 2.png
Labels: documentation, enhancement, hacktoberfest, no-code, hacktoberfest-accepted

#34 Updated Light Theme User Experience Design.md file
  User Experience/Design.md
Labels: good first issue, hacktoberfest, no-code, hacktoberfest-accepted

#37 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#48 add darkmode
  index.html
  main.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#55 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#58 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#68 feat(readme): add details and enhance structure
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#67 Update main.js to fix XSS
  main.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#69 Improved contributing.md file
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#71 syncing Master to Ideas
  CONTRIBUTING.md
  README.md
  main.js
Labels: hacktoberfest, hacktoberfest-accepted

#65 feat(voice-input): add voice handling for user
  images/microphone.png
  index.html
  main.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#73 Revert "Improved UI for Todo Items"
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#74 Changed the Placement of Dark Mode Toggle and CSS Fixes
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#81 added package.json without any dependencies
  package.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#83 Change Margin Position and Height
  style.css
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#87 Improved design and favicon
  images/favicon.png
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#90 Added Scrollbar.
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#97 Fixed whitespace bug
  main.js
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#100 Enhanced the layout of card and added CSS Effects to TODO
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#102 Changed the UI and Added Animations and transitions
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#105 Customized the dark mode button
  index.html
  main.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#109 Created issue template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#117 Created an about section for the website
  About.html
  about.css
  images/4380.jpg
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
